env:
  global:
    - CC_TEST_REPORTER_ID=78bce6519634f73083fdd1db6d79186e5041bc35733af13b5b7e7f27e25d292d
language: node_js
sudo: false
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  #- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - ./cc-test-reporter format-coverage -t lcov coverage/lcov.info
  - ./cc-test-reporter upload-coverage
node_js:
  - "8"
install:
  - npm install
script:
  - npm test
  - npm run coverage
